name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    name: Build ecub environment
    runs-on: ubuntu-latest

    steps:
      - name: Check space 1
        run: |
          echo "Free space:"
          df -h
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 1024
          swap-size-mb: 1024
          remove-dotnet: 'true'
          
      - name: Check space 2
        run: |
          echo "Free space:"
          df -h
          
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ecub-env:$(date +%s) 
    
